id: P001807
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:22:46.609341
source_metadata:
  id: bdr:W1AC9
  title: 'ལྷ་ལྡན་གཙུག་ལག་ཁང་། '
  author: ''
  volumes:
    a4af1d2c9a014af0999870985a6d7db1:
      image_group_id: I2PD18812
      title: ''
      volume_number: 1
      total_pages: 170
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
